CREATE TABLE dbo.FACTURA 
(
	IdFactura INT NOT NULL IDENTITY(1,1) 
		CONSTRAINT PK_Factura PRIMARY KEY CLUSTERED,
	IdContrato INT NOT NULL
        CONSTRAINT FK_FACTURA_CONTRATO
				FOREIGN KEY
				REFERENCES dbo.CONTRATO(IdContrato) , 
    FechaEmision DATE NOT NULL,
	--Periodo AS CAST( FORMAT(FechaEmision,'yyyyMM') AS int),
    FechaVencimiento DATETIME NOT NULL,
    MontoTotal DECIMAL(16,2) NOT NULL, 
    EstadoPago VARCHAR(20) NOT NULL
		CONSTRAINT CHK_FACTURA_EstadoContrato
			CHECK (EstadoPago in ( 'Pendiente','Pagado')  ),
	SysDateFrom DATETIME2 GENERATED ALWAYS AS ROW START,
    SysDateTo DATETIME2 GENERATED ALWAYS AS ROW END,
    PERIOD FOR SYSTEM_TIME (SysDateFrom, SysDateTo)
)
WITH (DATA_COMPRESSION  = PAGE,SYSTEM_VERSIONING = ON (HISTORY_TABLE=dbo.[FACTURA_HISTORY], DATA_CONSISTENCY_CHECK=ON))
GO

CREATE NONCLUSTERED INDEX IX_Factura_FechaEmision
ON FACTURA (FechaEmision)
INCLUDE (IdContrato, MontoTotal)
WITH (DATA_COMPRESSION  = PAGE);
GO