CREATE TABLE dbo.MANTENIMIENTO 
(
		IdMantenimiento INT NOT NULL IDENTITY(1,1) 
		CONSTRAINT PK_Mantenimiento PRIMARY KEY CLUSTERED,
		IdEquipo INT NOT NULL
             CONSTRAINT FK_MANTENIMIENTO_EQUIPO
				FOREIGN KEY
				REFERENCES dbo.EQUIPO(IdEquipo), 
        IdEmpleado INT NOT NULL
             CONSTRAINT FK_MANTENIMIENTO_EMPLEADO
				FOREIGN KEY
				REFERENCES dbo.EMPLEADO(IdEmpleado), 
        FechaMantenimiento DATETIME NOT NULL,
		FechaFinMantenimiento DATETIME NULL,
        IdTipoMantenimiento INT NOT NULL
			 CONSTRAINT FK_MANTENIMIENTO_TIPO_MANTENIMIENTO
				FOREIGN KEY
				REFERENCES dbo.TIPO_MANTENIMIENTO(IdTipoMantenimiento), 
        Descripcion VARCHAR(500), 
        Costo DECIMAL(16,2) NOT NULL,
		FechaCreacion DATETIME  CONSTRAINT DF_MANTENIMIENTO_FechaCreacion DEFAULT(GETDATE()),
		FechaModificacion DATETIME NULL
)
WITH (DATA_COMPRESSION  = PAGE)
GO