CREATE TABLE dbo.MANTENIMIENTO 
(
		IdMantenimiento INT NOT NULL IDENTITY(1,1) 
		CONSTRAINT PK_Mantenimiento PRIMARY KEY CLUSTERED,
		IdEquipo INT NOT NULL
             CONSTRAINT FK_MANTENIMIENTO_EQUIPO
				FOREIGN KEY
				REFERENCES dbo.EQUIPO(IdEquipo), 
        IdEmpleado INT NOT NULL
             CONSTRAINT FK_MANTENIMIENTO_EMPLEADO
				FOREIGN KEY
				REFERENCES dbo.EMPLEADO(IdEmpleado), 
        FechaMantenimiento DATETIME NOT NULL,
		FechaFinMantenimiento DATETIME NULL,
        IdTipoMantenimiento INT NOT NULL
			 CONSTRAINT FK_MANTENIMIENTO_TIPO_MANTENIMIENTO
				FOREIGN KEY
				REFERENCES dbo.TIPO_MANTENIMIENTO(IdTipoMantenimiento), 
        Descripcion VARCHAR(500), 
        Costo DECIMAL(16,2) NOT NULL,
		FechaCreacion DATETIME  CONSTRAINT DF_MANTENIMIENTO_FechaCreacion DEFAULT(GETDATE()),
		FechaModificacion DATETIME NULL,
		 SysDateFrom DATETIME2 GENERATED ALWAYS AS ROW START,
		 SysDateTo DATETIME2 GENERATED ALWAYS AS ROW END,
		 PERIOD FOR SYSTEM_TIME (SysDateFrom, SysDateTo)
)
WITH (DATA_COMPRESSION  = PAGE,SYSTEM_VERSIONING = ON (HISTORY_TABLE=dbo.MANTENIMIENTO_HISTORY, DATA_CONSISTENCY_CHECK=ON))
GO

CREATE NONCLUSTERED INDEX IX_Mantenimiento_IdEquipo
ON MANTENIMIENTO (IdEquipo)
INCLUDE (FechaMantenimiento, IdTipoMantenimiento, Costo, IdEmpleado)
WITH (DATA_COMPRESSION  = PAGE);

GO