CREATE TABLE dbo.PAGO
(
		IdPago INT NOT NULL IDENTITY(1,1) 
			CONSTRAINT PK_Pago PRIMARY KEY CLUSTERED,
		IdFactura INT NOT NULL
			 CONSTRAINT FK_Pago_FACTURA
				FOREIGN KEY
				REFERENCES dbo.FACTURA(IdFactura) , 
        FechaPago DATETIME NOT NULL , 
        MontoPagado DECIMAL(16,2) NOT NULL, 
        IdMetodoPago INT NOT NULL
			 CONSTRAINT FK_Pago_MetodoPago
				FOREIGN KEY
				REFERENCES dbo.METODO_PAGO(IdMetodoPago)
)
WITH (DATA_COMPRESSION  = PAGE)
GO