CREATE TABLE dbo.TIPO_RECLAMO
(
	IdTipoReclamo INT NOT NULL IDENTITY(1,1) 
		CONSTRAINT PK_TipoReclamo PRIMARY KEY CLUSTERED,
		NombreTipoReclamo VARCHAR(200) NOT NULL
)
WITH (DATA_COMPRESSION  = PAGE)
GO