CREATE TABLE dbo.SERVICIO
(
		IdServicio INT NOT NULL IDENTITY(1,1) 
			CONSTRAINT PK_Servicio PRIMARY KEY CLUSTERED,
		IdContrato INT NOT NULL
			CONSTRAINT FK_SERVICIO_CONTRATO
				FOREIGN KEY
				REFERENCES dbo.CONTRATO(IdContrato), 
        IdTipoServicio INT NOT NULL
			CONSTRAINT FK_SERVICIO_TipoServicio
				FOREIGN KEY
				REFERENCES dbo.TIPO_SERVICIO(IdTipoServicio),  
        FechaInstalacion DATETIME  NULL, 
)
WITH (DATA_COMPRESSION  = PAGE)
GO