CREATE TABLE dbo.TIPO_SERVICIO
(
	IdTipoServicio INT NOT NULL IDENTITY(1,1) 
		CONSTRAINT PK_TipoServicio PRIMARY KEY CLUSTERED,
	NombreServicio VARCHAR(200) NOT NULL,
	Tarifa Decimal(16,2)
)
WITH (DATA_COMPRESSION  = PAGE)
GO